# Generated by Django 6.0.2 on 2026-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Tarjeta de Crédito"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Transferencia Bancaria"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="COMPLETED", max_length=20)),
                ("response_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
