# Generated by Django 6.0.4 on 2026-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_action",
                    models.CharField(max_length=100, verbose_name="Acción Realizada"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha/Hora"),
                ),
                ("details", models.JSONField(verbose_name="Detalles de ejecución")),
            ],
            options={
                "verbose_name": "Estado del Hogar",
                "verbose_name_plural": "Estados del Hogar",
                "ordering": ["-activated_at"],
            },
        ),
    ]
