# Generated by Django 6.0.2 on 2026-04-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logging_provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="level",
            field=models.CharField(
                choices=[("info", "Info"), ("error", "Error")],
                default="info",
                max_length=10,
            ),
        ),
    ]
