# Generated by Django 6.0.2 on 2026-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("distance", models.FloatField()),
                (
                    "strategy_used",
                    models.CharField(
                        choices=[("fedex", "FedEx"), ("ups", "UPS"), ("dhl", "DHL")],
                        max_length=10,
                    ),
                ),
                ("calculated_cost", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro de Envío",
                "verbose_name_plural": "Registros de Envíos",
                "ordering": ["-created_at"],
            },
        ),
    ]
